### ISSUE TITLE
where is segmentation folder ?

### ISSUE THREAD

**Issue by Cloveryww** [hunto/MasKD#4]
Thanks for your nice work firstly!!
I want to know where is segmentation folder and if all codes abount masKD in semantic segmentaton task has been release?

BR
<img width="509" alt="image" src="https://user-images.githubusercontent.com/24958159/226524402-4995dd25-ffc0-48f6-97d4-14d3ad7e8137.png">

**Comment by hunto** [comment]
Sorry, we forgot to release the segmentation code. I'm preparing the segmentation code now, and it will be upload within one week.

Besides, our segmentation code is based on the code [here](https://github.com/hunto/DIST_KD/tree/main/segmentation), which may be helpful for your reference.

**Comment by Cloveryww** [comment]
Looking forward to your update！！

**Comment by serser** [comment]
@hunto Hi, will the seg code be open soon?

**Comment by hunto** [comment]
Hi @Cloveryww @serser ,

Sorry for the late update since we are busy on other projects.

The segmentation code (including knowledge distillation, learning mask module, visualizing masks) is uploaded. We also provide the learned mask module checkpoint for re-implementing our results.

If you have any question, please feel free to contact us :)

**Comment by hunto** [comment]
I close this issue since the segmentation code is uploaded. If you have further questions, please feel free to reopen this issue or open a new issue. Thanks :)
