### ISSUE TITLE
Can not reproduce your result

### ISSUE THREAD

**Issue by songyang86** [hunto/MasKD#5]
dear hunto,when I run your code about Faster RCNN-R101.py,I got worse result.

**Comment by songyang86** [comment]
looking forword your reply.

**Comment by Gumpest** [comment]
Hi, songyang86. May I ask what your result is?  The reason is that the result [41.0] in table is adopted with inheriting strategy, but the config [40.8] our provided is **NOT** added with inheriting strategy.  If you want to achieve 41.0 by MasKD, we can provide the config added with inheriting strategy.
